-- Generated by .assets-src/build-subservice-images.mjs — do not edit by hand.
-- Hero photo for each of the nine sub-service pages, taken from the live
-- site and re-encoded as WebP. Picked by excluding images shared across
-- pages, then taking the largest remaining photograph.
USE `aertoit`;

UPDATE `services` SET
  `hero_image` = '/assets/services/couverture-en-tuiles.webp',
  `hero_image_alt` = 'Toiture en tuiles mécaniques en terre cuite posée par Aertoit'
WHERE `slug` = 'couverture-en-tuiles';

UPDATE `services` SET
  `hero_image` = '/assets/services/couverture-en-ardoises.webp',
  `hero_image_alt` = 'Couverture en ardoises sur une maison en cours de rénovation'
WHERE `slug` = 'couverture-en-ardoises';

UPDATE `services` SET
  `hero_image` = '/assets/services/couverture-en-bac-acier.webp',
  `hero_image_alt` = 'Couverture en bac acier avec gouttière et descente d’eau'
WHERE `slug` = 'couverture-en-bac-acier';

UPDATE `services` SET
  `hero_image` = '/assets/services/solutions-d-isolation-laine-de-verre.webp',
  `hero_image_alt` = 'Panneau de laine de verre destiné à l’isolation de toiture'
WHERE `slug` = 'solutions-d-isolation-laine-de-verre';

UPDATE `services` SET
  `hero_image` = '/assets/services/solutions-d-isolation-laine-de-roche.webp',
  `hero_image_alt` = 'Laine de roche projetée dans des combles perdus'
WHERE `slug` = 'solutions-d-isolation-laine-de-roche';

UPDATE `services` SET
  `hero_image` = '/assets/services/solutions-d-isolation-sarking-fibre-de-bois.webp',
  `hero_image_alt` = 'Panneaux de fibre de bois posés en sarking sur une toiture'
WHERE `slug` = 'solutions-d-isolation-sarking-fibre-de-bois';

UPDATE `services` SET
  `hero_image` = '/assets/services/solutions-d-isolation-sarking-polyurethane.webp',
  `hero_image_alt` = 'Panneaux de polyuréthane posés en sarking sur une charpente'
WHERE `slug` = 'solutions-d-isolation-sarking-polyurethane';

UPDATE `services` SET
  `hero_image` = '/assets/services/solutions-d-isolation-actis.webp',
  `hero_image_alt` = 'Isolant mince Actis posé entre chevrons'
WHERE `slug` = 'solutions-d-isolation-actis';

UPDATE `services` SET
  `hero_image` = '/assets/services/accessoires-velux.webp',
  `hero_image_alt` = 'Fenêtre de toit VELUX avec store intégré sur une toiture en tuiles'
WHERE `slug` = 'accessoires-velux';

SELECT `slug`, `hero_image` IS NOT NULL AS has_photo
FROM `services` WHERE `parent_id` IS NOT NULL ORDER BY `sort_order`;
