-- Generated by .assets-src/extract-remaining.py — do not edit by hand.
-- The last two content gaps: the homepage 'Savoir-faire français' block,
-- and the sub-service card excerpts as worded on the parent pages.
USE `aertoit`;

INSERT INTO `pages` (`slug`, `h1`, `intro`, `meta_title`, `meta_description`, `is_published`)
VALUES ('savoir-faire-francais', 'Savoir-faire français', 'Aertoit met en avant l''excellence du savoir-faire local en travaillant avec des professionnels expérimentés. Nous assurons un travail de haute qualité en respectant rigoureusement les normes et en valorisant le patrimoine architectural français.',
        'Savoir-faire français', 'Aertoit met en avant l''excellence du savoir-faire local en travaillant avec des professionnels expérimentés. Nous assurons un travail de haute qualité en respectant rigoureusement les normes et en valorisant le patrimoine architectural français.', TRUE)
ON DUPLICATE KEY UPDATE `h1` = VALUES(`h1`), `intro` = VALUES(`intro`);

UPDATE `services` SET `card_excerpt` = 'Une couverture élégante et intemporelle pour une protection optimale.' WHERE `slug` = 'couverture-en-ardoises';
UPDATE `services` SET `card_excerpt` = 'Optez pour la tradition et la durabilité avec nos toitures en tuiles.' WHERE `slug` = 'couverture-en-tuiles';
UPDATE `services` SET `card_excerpt` = 'Robustesse et légèreté pour une toiture moderne et performante.' WHERE `slug` = 'couverture-en-bac-acier';
UPDATE `services` SET `card_excerpt` = 'Une isolation naturelle et écologique pour un confort thermique durable.' WHERE `slug` = 'solutions-d-isolation-sarking-fibre-de-bois';
UPDATE `services` SET `card_excerpt` = 'L’isolation extérieure idéale pour des performances thermiques exceptionnelles.' WHERE `slug` = 'solutions-d-isolation-sarking-polyurethane';
UPDATE `services` SET `card_excerpt` = 'Une isolation multicouche innovante et polyvalente pour votre maison.' WHERE `slug` = 'solutions-d-isolation-actis';
UPDATE `services` SET `card_excerpt` = 'Une isolation résistante au feu et performante sur le long terme.' WHERE `slug` = 'solutions-d-isolation-laine-de-roche';
UPDATE `services` SET `card_excerpt` = 'Une solution classique pour une isolation thermique et acoustique efficace.' WHERE `slug` = 'solutions-d-isolation-laine-de-verre';
UPDATE `services` SET `card_excerpt` = 'Stores et volets pour un confort et une protection optimisés.' WHERE `slug` = 'accessoires-velux';

SELECT slug, LEFT(card_excerpt, 62) AS card_excerpt
FROM `services` WHERE parent_id IS NOT NULL ORDER BY sort_order;
