"""
Recovers the last two content gaps found by verify-content.py:

  1. The "Savoir-faire français" block on the homepage, which the rebuild
     never had.
  2. The sub-service card excerpts as written on the *parent* pages. The
     rebuild used each child's meta description instead, which is different
     wording — so the parent pages read differently from the live site.

Writes 018-remaining-content.sql.
"""
import io
import re
import urllib.request
from html.parser import HTMLParser

BASE = "https://aertoit.fr"
SKIP = {"script", "style", "noscript", "svg", "head"}
BLOCKS = {"h1", "h2", "h3", "h4", "p", "li"}


class P(HTMLParser):
    def __init__(self):
        super().__init__()
        self.skip = 0
        self.stack = []
        self.buf = []
        self.blocks = []

    def handle_starttag(self, t, a):
        if t in SKIP:
            self.skip += 1
        elif not self.skip and t in BLOCKS:
            self.stack.append(t)
            self.buf = []

    def handle_endtag(self, t):
        if t in SKIP:
            self.skip = max(0, self.skip - 1)
        elif not self.skip and t in BLOCKS and self.stack and self.stack[-1] == t:
            self.stack.pop()
            s = re.sub(r"\s+", " ", "".join(self.buf)).strip()
            if len(s) > 2:
                self.blocks.append((t, s))
            self.buf = []

    def handle_data(self, d):
        if not self.skip and self.stack:
            self.buf.append(d)


def blocks(path):
    req = urllib.request.Request(BASE + path, headers={"User-Agent": "Mozilla/5.0"})
    p = P()
    p.feed(urllib.request.urlopen(req, timeout=45).read().decode("utf-8", "replace"))
    return p.blocks


def esc(s):
    return s.replace("\\", "\\\\").replace("'", "''")


# --- 1. Savoir-faire français ------------------------------------------
home = blocks("/")
savoir_title, savoir_body = None, None
for i, (tag, text) in enumerate(home):
    if re.match(r"^Savoir-faire fran", text, re.I):
        savoir_title = text
        for _t2, t2 in home[i + 1:i + 4]:
            if len(t2) > 60:
                savoir_body = t2
                break
        break

print("1. Savoir-faire français")
print(f"   title: {savoir_title}")
print(f"   body : {(savoir_body or '')[:110]}…\n")

# --- 2. card excerpts as written on the parent pages --------------------
PARENTS = {
    "/couverture": ["couverture-en-tuiles", "couverture-en-ardoises", "couverture-en-bac-acier"],
    "/isolation": [
        "solutions-d-isolation-laine-de-verre", "solutions-d-isolation-laine-de-roche",
        "solutions-d-isolation-sarking-fibre-de-bois",
        "solutions-d-isolation-sarking-polyurethane", "solutions-d-isolation-actis",
    ],
    "/fenetre-de-toit-velux": ["accessoires-velux"],
}
NAME_TO_SLUG = {
    "Couverture en Tuiles": "couverture-en-tuiles",
    "Couverture en Ardoises": "couverture-en-ardoises",
    "Couverture en Bac Acier": "couverture-en-bac-acier",
    "Isolation en Laine de Verre": "solutions-d-isolation-laine-de-verre",
    "Isolation par Laine de Roche Projetée": "solutions-d-isolation-laine-de-roche",
    "Isolation en Sarking Fibre de Bois": "solutions-d-isolation-sarking-fibre-de-bois",
    "Isolation en Sarking Polyuréthane": "solutions-d-isolation-sarking-polyurethane",
    "Isolation Mince Actis": "solutions-d-isolation-actis",
    "Accessoires VELUX": "accessoires-velux",
}

excerpts = {}
for parent_path in PARENTS:
    bs = blocks(parent_path)
    for i, (_tag, text) in enumerate(bs):
        slug = NAME_TO_SLUG.get(text)
        if not slug or slug in excerpts:
            continue
        # The card's one-line description is the next block of real length.
        for _t2, t2 in bs[i + 1:i + 3]:
            if 20 < len(t2) < 200 and t2 not in NAME_TO_SLUG:
                excerpts[slug] = t2
                break

print(f"2. card excerpts recovered: {len(excerpts)} of {len(NAME_TO_SLUG)}")
for slug, text in excerpts.items():
    print(f"   {slug:<46} {text[:60]}")

# --- write SQL ----------------------------------------------------------
out = io.open("../database/migrations/018-remaining-content.sql", "w", encoding="utf-8")
out.write("-- Generated by .assets-src/extract-remaining.py — do not edit by hand.\n")
out.write("-- The last two content gaps: the homepage 'Savoir-faire français' block,\n")
out.write("-- and the sub-service card excerpts as worded on the parent pages.\n")
out.write("USE `aertoit`;\n\n")

if savoir_title and savoir_body:
    out.write(f"""INSERT INTO `pages` (`slug`, `h1`, `intro`, `meta_title`, `meta_description`, `is_published`)
VALUES ('savoir-faire-francais', '{esc(savoir_title)}', '{esc(savoir_body)}',
        'Savoir-faire français', '{esc(savoir_body[:300])}', TRUE)
ON DUPLICATE KEY UPDATE `h1` = VALUES(`h1`), `intro` = VALUES(`intro`);\n\n""")

for slug, text in excerpts.items():
    out.write(f"UPDATE `services` SET `card_excerpt` = '{esc(text)}' WHERE `slug` = '{esc(slug)}';\n")

out.write("""
SELECT slug, LEFT(card_excerpt, 62) AS card_excerpt
FROM `services` WHERE parent_id IS NOT NULL ORDER BY sort_order;
""")
out.close()
print("\nwrote 018-remaining-content.sql")
