"""
Generates 004-subservices.sql from the extracted page content.

Body copy is taken from the live pages rather than rewritten, so the nine
sub-service pages carry their real text. Site chrome (nav labels, CTA
buttons, the commune rotator, footer) is filtered out — those are layout,
not page content.

    python gen-subservices.py > ../database/migrations/004-subservices.sql
"""
import json
import io
import os
import re

CONTENT = "content"

# slug -> (parent slug, file, sort)
SUBS = [
    ("couverture-en-tuiles", "couverture", 1),
    ("couverture-en-ardoises", "couverture", 2),
    ("couverture-en-bac-acier", "couverture", 3),
    ("solutions-d-isolation-laine-de-verre", "isolation", 1),
    ("solutions-d-isolation-laine-de-roche", "isolation", 2),
    ("solutions-d-isolation-sarking-fibre-de-bois", "isolation", 3),
    ("solutions-d-isolation-sarking-polyurethane", "isolation", 4),
    ("solutions-d-isolation-actis", "isolation", 5),
    ("accessoires-velux", "fenetre-de-toit-velux", 1),
]

# Chrome that appears on every page and is not page content.
CHROME = {
    "accueil", "nos services", "a propos", "à propos", "recrutement", "contact",
    "demande de devis", "demande de devis rapide", "plus d'informations",
    "je souhaite être rappelé(e)", "en savoir plus", "nos prestations",
    "navigation", "services", "avis clients", "tous droits réservés",
    "l'énergie est notre avenir, économisons la.",
}
# The rotating commune headings — layout, stored separately as data.
COMMUNE_RE = re.compile(r"^(dans le val-de-marne|au? |à |aux )", re.I)


def esc(s):
    return (s or "").replace("\\", "\\\\").replace("'", "''")


def clean(text):
    return re.sub(r"\s+", " ", text).strip()


def build(slug):
    path = os.path.join(CONTENT, "service__" + slug + ".json")
    with io.open(path, encoding="utf-8") as f:
        d = json.load(f)

    h1 = next((b["text"] for b in d["blocks"] if b["tag"] == "h1"), slug)

    body, seen, dropped_h1 = [], set(), False
    for b in d["blocks"]:
        t = clean(b["text"])
        low = t.lower()
        if low in CHROME or len(t) < 3:
            continue
        # The template renders the H1; keeping it in the body repeated it as
        # a stray paragraph at the top of every sub-service page.
        if not dropped_h1 and t == h1:
            dropped_h1 = True
            seen.add(t)
            continue
        if b["tag"] in ("h1", "h2") and COMMUNE_RE.match(t) and len(t) < 34:
            continue          # commune rotator entry
        if t in seen:
            continue
        seen.add(t)
        if b["tag"] in ("h2", "h3", "h4"):
            # Preserve the level rather than flattening to <h2>.
            body.append(f'<{b["tag"]}>{t}</{b["tag"]}>')
        elif b["tag"] == "li":
            body.append(f"<li>{t}</li>")
        else:
            body.append(f"<p>{t}</p>")

    # wrap consecutive <li> runs in a <ul>
    html, in_list = [], False
    for chunk in body:
        is_li = chunk.startswith("<li>")
        if is_li and not in_list:
            html.append("<ul>")
            in_list = True
        elif not is_li and in_list:
            html.append("</ul>")
            in_list = False
        html.append(chunk)
    if in_list:
        html.append("</ul>")

    intro = next(
        (clean(b["text"]) for b in d["blocks"]
         if b["tag"] == "p" and len(clean(b["text"])) > 60), d["description"] or "")

    return {
        "h1": h1,
        "title": d["title"] or h1,
        "desc": (d["description"] or "")[:300],
        "intro": intro[:600],
        "body": "".join(html),
    }


print("-- Generated by .assets-src/gen-subservices.py — do not edit by hand.")
print("-- Nine sub-service pages recovered from the live site (absent from its sitemap).")
print("USE `aertoit`;\n")

for slug, parent, order in SUBS:
    d = build(slug)
    name = d["h1"]
    print(f"""INSERT INTO `services`
  (`parent_id`, `slug`, `name`, `h1`, `card_title`, `card_excerpt`, `intro`, `body`,
   `meta_title`, `meta_description`, `sort_order`, `is_published`)
SELECT p.id, '{esc(slug)}', '{esc(name)}', '{esc(d["h1"])}', '{esc(name)}',
       '{esc(d["desc"][:380])}', '{esc(d["intro"])}', '{esc(d["body"])}',
       '{esc(d["title"])}', '{esc(d["desc"])}', {order}, TRUE
FROM `services` p WHERE p.slug = '{esc(parent)}'
ON DUPLICATE KEY UPDATE
  `parent_id` = VALUES(`parent_id`), `name` = VALUES(`name`), `h1` = VALUES(`h1`),
  `card_title` = VALUES(`card_title`), `card_excerpt` = VALUES(`card_excerpt`),
  `intro` = VALUES(`intro`), `body` = VALUES(`body`),
  `meta_title` = VALUES(`meta_title`), `meta_description` = VALUES(`meta_description`),
  `sort_order` = VALUES(`sort_order`);
""")

print("""SELECT p.slug AS parent, c.slug AS child, CHAR_LENGTH(c.body) AS body_chars
FROM `services` c LEFT JOIN `services` p ON p.id = c.parent_id
WHERE c.parent_id IS NOT NULL ORDER BY p.sort_order, c.sort_order;""")
