"""
Seeds the à-propos page row from the live site.

Adds an id to the "Vous Souhaitez Nous Rejoindre ?" heading so the header's
Recrutement link (/a-propos#recrutement) has a real target, and corrects the
"Satifaction" typo carried by the live page.

    python gen-apropos.py
"""
import io
import re

src = io.open("extract-all.py", encoding="utf-8").read()
ns = {}
exec(src.split("sql = io.open")[0], ns)  # reuse the extractor, not its main body

html = ns["body_html"]("https://aertoit.fr/a-propos", drop_first_heading=True)

# Anchor target for the Recrutement nav item.
html = html.replace(
    "<h2>Vous Souhaitez Nous Rejoindre ?</h2>",
    '<h2 id="recrutement">Vous Souhaitez Nous Rejoindre ?</h2>',
)
# Typo on the live page.
html = html.replace("Satifaction", "Satisfaction")

intro_match = re.search(r"<p>(.{80,400}?)</p>", html)
intro = intro_match.group(1) if intro_match else ""


def esc(s):
    return (s or "").replace("\\", "\\\\").replace("'", "''")


sql = io.open("../database/migrations/008-apropos.sql", "w", encoding="utf-8")
sql.write("-- Generated by .assets-src/gen-apropos.py — do not edit by hand.\n")
sql.write("USE `aertoit`;\n\n")
sql.write(f"""INSERT INTO `pages`
  (`slug`, `h1`, `intro`, `body`, `meta_title`, `meta_description`)
VALUES (
  'a-propos',
  'À Propos d''Aertoit Couverture',
  '{esc(intro)}',
  '{esc(html)}',
  'À propos d''Aertoit Couverture — Couvreurs dans le Val-de-Marne',
  'Découvrez Aertoit Couverture, votre expert en travaux de toiture, charpente, isolation et étanchéité. Une expertise française depuis 2005.'
)
ON DUPLICATE KEY UPDATE
  `h1` = VALUES(`h1`), `intro` = VALUES(`intro`), `body` = VALUES(`body`),
  `meta_title` = VALUES(`meta_title`), `meta_description` = VALUES(`meta_description`);

SELECT `slug`, CHAR_LENGTH(`body`) AS body_chars,
       `body` LIKE '%id="recrutement"%' AS has_anchor
FROM `pages`;
""")
sql.close()

heads = re.findall(r"<h2[^>]*>(.*?)</h2>", html)
print(f"body: {len(html)} chars, {html.count('<p>')} paragraphs, {len(heads)} headings")
for h in heads:
    print("  -", h[:70])
